# Getting started with TensorFlow

In [1]:
import tensorflow as tf
import numpy as np
a = np.array([5,3,8])
b = np.array([3,-1,2])
c = np.add(a,b)
print c

[ 8  2 10]


In [4]:
a = tf.constant([5.0,3.0,8.0])
b = tf.constant([3.0,-1.0,2.0])
c = tf.add(a,b)
print c
with tf.Session() as sess:
  result = sess.run(c)
  print result

Tensor("Add_2:0", shape=(3,), dtype=float32)
[  8.   2.  10.]


In [6]:
a = tf.placeholder(dtype=tf.int32, shape=(None,))  # batchsize x scalar
b = tf.placeholder(dtype=tf.int32, shape=(None,))
c = tf.add(a, b)
with tf.Session() as sess:
  result = sess.run(c, feed_dict={
      a: [3, 4, 5],
      b: [-1, 9, 3]
    })
  print result

[ 2 13  8]


# Heron's formula

In [ ]:
def compute_area(sides):
  a = sides[:,0]
  b = sides[:,1]
  c = sides[:,2]
  s = tf.add(a,tf.add(b,c))*0.5
  areasq = s*(s-a)*(s-b)*(s-c)
  return tf.sqrt(areasq)

with tf.Session() as sess:
  area = compute_area(tf.constant([[5.0,3.0,7.1],[2.3,4.1,4.8]]))
  result = sess.run(area)
  print result